services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoAddressVerification\:
        resource: ../../
        exclude: ../../{ContaoManager,Resources}
