services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoAddressVerification\:
        resource: ../src
        exclude: ../src/{ContaoManager,Resources}
