services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $nodeManager: '@terminal42_node.manager'
    
    InspiredMinds\ContaoAddressVerification\:
        resource: ../src
        exclude: ../src/{ContaoManager,Event,Model,Resources}

    InspiredMinds\ContaoAddressVerification\Controller\:
        resource: ../src/Controller
        tags: ['controller.service_arguments']
